version: '3'

services:
  frontend:
    build: ./mess-frontend
    ports:
      - "5000:5000"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - mess-network
    restart: always

  backend:
    build: ./mess-backend
    ports:
      - "8000:8000"
    networks:
      - mess-network
    restart: always

networks:
  mess-network:
    driver: bridge