apiVersion: v1
kind: Service
metadata:
  name: mess-backend-service
  labels:
    app: mess-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: mess-backend
