apiVersion: apps/v1
kind: Deployment
metadata:
  name: mess-backend
  labels:
    app: mess-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mess-backend
  template:
    metadata:
      labels:
        app: mess-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: mess-backend
        image: ${ECR_REPOSITORY_URI}/mess-backend:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5