apiVersion: v1
kind: Service
metadata:
  name: mess-frontend-service
  labels:
    app: mess-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: mess-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mess-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: mess-frontend-service
            port:
              number: 80
