apiVersion: apps/v1
kind: Deployment
metadata:
  name: mess-frontend
  labels:
    app: mess-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mess-frontend
  template:
    metadata:
      labels:
        app: mess-frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: mess-frontend
        image: ${ECR_REPOSITORY_URI}/mess-frontend:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        env:
        - name: API_URL
          value: "http://mess-backend-service:8000"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5