---
all:
  children:
    eks_workers:
      hosts:
        worker1:
          ansible_host: worker1.example.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        worker2:
          ansible_host: worker2.example.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ec2_instances:
      hosts:
        instance1:
          ansible_host: instance1.example.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        instance2:
          ansible_host: instance2.example.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
  vars:
    ansible_python_interpreter: /usr/bin/python3